import React, { useState } from "react";
import { View, Text, StyleSheet, Pressable, Platform } from "react-native";
import { fonts } from "../theme/fonts";
import { colors, cardShadow } from "../theme/ui";

type Rec = { id: string; zone: string; action: string; reason: string; impact: string; priority: "High" | "Medium" | "Low"; status: "Pending" | "Approved" | "Dismissed" };

const INITIAL: Rec[] = [
	{ id: "1", zone: "Zone 2 — Slab", action: "Lower setpoint to 21.5°C for 90 minutes", reason: "Predicted grid peak + high thermal mass buffer", impact: "−4.2 kWh/day · 92% confidence", priority: "High", status: "Pending" },
	{ id: "2", zone: "HRV1-3", action: "Extend night purge +45m", reason: "Cool overnight air available · free cooling window", impact: "−6.0 kWh/day · 88% confidence", priority: "High", status: "Pending" },
	{ id: "3", zone: "AHU-2", action: "Peak shave fan speed −12%", reason: "Demand response event forecast 16:00–18:00", impact: "−3.1 kWh/day · 81% confidence", priority: "Medium", status: "Pending" },
	{ id: "4", zone: "Zone 1 — Core", action: "Pre-cool to 20.8°C before occupancy", reason: "Morning load shift opportunity", impact: "−2.4 kWh/day · 76% confidence", priority: "Medium", status: "Approved" },
	{ id: "5", zone: "Zone 4", action: "Hold damper at 40% during DR window", reason: "Low occupancy · CO₂ stable", impact: "−1.1 kWh/day · 70% confidence", priority: "Low", status: "Dismissed" },
];

export function DSMPage() {
	const [recs, setRecs] = useState(INITIAL);
	const open = recs.filter((r) => r.status === "Pending").length;
	const setStatus = (id: string, status: Rec["status"]) => setRecs((list) => list.map((r) => (r.id === id ? { ...r, status } : r)));
	return (
		<View style={styles.wrap}>
			<Text style={styles.title}>DSM Recommendations</Text>
			<Text style={styles.sub}>Automation proposals generated by the ARIS optimization engine</Text>
			<View style={styles.kpis}>
				{[
					["OPEN RECOMMENDATIONS", String(open)],
					["POTENTIAL SAVINGS", "16.1", "kWh/day"],
					["REALIZED SAVINGS", "2.8", "kWh/day"],
				].map(([l, v, u]) => (
					<View key={l} style={styles.kpi}>
						<Text style={styles.kpiLabel}>{l}</Text>
						<Text style={styles.kpiValue}>
							{v}
							{u ? <Text style={styles.kpiUnit}> {u}</Text> : null}
						</Text>
					</View>
				))}
			</View>
			<Text style={styles.queueTitle}>Recommendation Queue</Text>
			{recs.map((r) => (
				<View key={r.id} style={styles.card}>
					<View style={styles.cardTop}>
						<Text style={styles.zone}>{r.zone}</Text>
						<View style={styles.tags}>
							<View style={[styles.tag, r.priority === "High" ? styles.tagHigh : r.priority === "Medium" ? styles.tagMed : styles.tagLow]}>
								<Text style={styles.tagText}>{r.priority}</Text>
							</View>
							<View style={[styles.tag, r.status === "Pending" ? styles.tagPend : r.status === "Approved" ? styles.tagOk : styles.tagOff]}>
								<Text style={styles.tagText}>{r.status}</Text>
							</View>
						</View>
					</View>
					<Text style={styles.action}>{r.action}</Text>
					<Text style={styles.reason}>{r.reason}</Text>
					<View style={styles.cardBottom}>
						<Text style={styles.impact}>{r.impact}</Text>
						{r.status === "Pending" ? (
							<View style={styles.actions}>
								<Pressable style={styles.approve} onPress={() => setStatus(r.id, "Approved")}>
									<Text style={styles.approveText}>Approve</Text>
								</Pressable>
								<Pressable style={styles.decline} onPress={() => setStatus(r.id, "Dismissed")}>
									<Text style={styles.declineText}>Decline</Text>
								</Pressable>
							</View>
						) : null}
					</View>
				</View>
			))}
		</View>
	);
}

const styles = StyleSheet.create({
	wrap: { gap: 14 },
	title: { fontFamily: fonts.bold, fontWeight: "700", fontSize: 28, color: colors.navy },
	sub: { fontFamily: fonts.regular, fontSize: 13, color: colors.muted, marginTop: -6 },
	kpis: { flexDirection: "row", gap: 12, flexWrap: "wrap" },
	kpi: { flex: 1, minWidth: 160, backgroundColor: "#fff", borderRadius: 12, padding: 16, ...cardShadow() },
	kpiLabel: { fontFamily: fonts.medium, fontSize: 11, color: "rgba(12,35,64,0.7)" },
	kpiValue: { fontFamily: fonts.bold, fontWeight: "700", fontSize: 28, color: colors.navy, marginTop: 4 },
	kpiUnit: { fontSize: 13, fontFamily: fonts.regular, color: colors.muted },
	queueTitle: { fontFamily: fonts.bold, fontWeight: "700", fontSize: 16, color: colors.navy, marginTop: 4 },
	card: { backgroundColor: "#fff", borderRadius: 12, borderWidth: 1, borderColor: colors.border, padding: 16, gap: 6 },
	cardTop: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: 12 },
	zone: { fontFamily: fonts.semibold, fontWeight: "600", fontSize: 14, color: colors.primary, flex: 1 },
	tags: { flexDirection: "row", gap: 6 },
	tag: { borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
	tagHigh: { backgroundColor: "rgba(220,53,69,0.12)" },
	tagMed: { backgroundColor: "rgba(111,66,193,0.12)" },
	tagLow: { backgroundColor: "rgba(0,163,224,0.12)" },
	tagPend: { backgroundColor: "rgba(111,66,193,0.12)" },
	tagOk: { backgroundColor: "rgba(0,94,184,0.12)" },
	tagOff: { backgroundColor: "rgba(108,117,125,0.15)" },
	tagText: { fontFamily: fonts.medium, fontSize: 11, color: colors.text },
	action: { fontFamily: fonts.medium, fontWeight: "500", fontSize: 14, color: colors.navy },
	reason: { fontFamily: fonts.regular, fontSize: 12, color: colors.muted },
	cardBottom: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 8, flexWrap: "wrap", gap: 10 },
	impact: { fontFamily: fonts.semibold, fontWeight: "600", fontSize: 12, color: colors.muted },
	actions: { flexDirection: "row", gap: 8 },
	approve: { backgroundColor: colors.primary, borderRadius: 8, paddingHorizontal: 14, paddingVertical: 8, ...(Platform.OS === "web" ? { cursor: "pointer" as any } : null) },
	approveText: { color: "#fff", fontFamily: fonts.semibold, fontWeight: "600", fontSize: 13 },
	decline: { borderWidth: 1, borderColor: colors.border, borderRadius: 8, paddingHorizontal: 14, paddingVertical: 8, backgroundColor: "#fff" },
	declineText: { color: colors.navy, fontFamily: fonts.medium, fontWeight: "500", fontSize: 13 },
});
